apiVersion: v1
kind: Pod
metadata:
 name: multi-container
 labels: 
  project: roboshop
  purpose: multi-conainer-demo
spec:
 containers:
 - name: nginx
   image: nginx
 - name: almalinux
   image: almalinux:9 
   command: ["sleep", "1000"]
   #almalinux is just os to make the container busy i used sleep.

